# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
                ('mimetype', models.CharField(default='', max_length=20)),
                ('sender', models.CharField(default='', max_length=30)),
                ('body', models.TextField(default='')),
                ('processed', models.IntegerField(default=0)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inbox',
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
                ('mimetype', models.CharField(default='', max_length=20)),
                ('receiver', models.CharField(default='', max_length=30)),
                ('body', models.TextField(default='')),
                ('chat_found', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'outbox',
            },
        ),
    ]
