# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openroad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='category',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='category',
        ),
    ]
