# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openroad', '0002_auto_20180605_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='mimetype',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='mimetype',
        ),
    ]
